
let getFacilities = function getFacilities() {
  return [
    {"name": "Avoyelles Correctional Center DC3", "city": "Cottonport", "state": "LA"},
    {"name": "Avoyelles Parish Detention Marksville DC1", "city": "Marksville", "state": "LA"},
    {"name": "Bayou Dorcheat Correctional Center", "city": "Minden", "state": "LA"},
    {"name": "Ben Hill County Jail", "city": "Fitzgerald", "state": "GA"},
    {"name": "Benton County Jail", "city": "Bentonville", "state": "AR"},
    {"name": "Bowie County Correctional", "city": "Texarkana", "state": "TX"},
    {"name": "Bowie Recovery Center", "city": "Texarkana", "state": "TX"},
    {"name": "Caldwell Parish Detention Center", "city": "Grayson", "state": "LA"},
    {"name": "Catahoula Correctional Center", "city": "Harrisonburg", "state": "LA"},
    {"name": "Claiborne Parish Detention Center", "city": "Homer", "state": "LA"},
    {"name": "Cleburne County Detention Center", "city": "Heber Springs", "state": "AR"},
    {"name": "Comal County Jail", "city": "New Braunfels", "state": "TX"},
    {"name": "Concordia Parish Correctional Facility", "city": "Ferriday", "state": "LA"},
    {"name": "Concordia Parish Jail", "city": "Vidalia", "state": "LA"},
    {"name": "Craighead County Detention", "city": "Jonesboro", "state": "AR"},
    {"name": "Crawford County Jail", "city": "Van Buren", "state": "AR"},
    {"name": "Dequincy Police Dept", "city": "Dequincy", "state": "LA"},
    {"name": "Dyer County Work Center", "city": "Dyersburg", "state": "TN"},
    {"name": "Franklin Parish Detention Center", "city": "Winnsboro", "state": "LA"},
    {"name": "Irwin County Detention Center", "city": "Ocilla", "state": "GA"},
    {"name": "Jack Harwell Detention Center", "city": "Waco", "state": "TX"},
    {"name": "Jackson Parish Correctional Center - Phase 1", "city": "Jonesboro", "state": "LA"},
    {"name": "Jackson Parish Correctional Center - Phase 2", "city": "Jonesboro", "state": "LA"},
    {"name": "Jeff Davis County Jail", "city": "Hazlehurst", "state": "GA"},
    {"name": "Lamar County Jail", "city": "Purvis", "state": "MS"},
    {"name": "LaSalle Correctional Center", "city": "Olla", "state": "LA"},
    {"name": "Liberty County Jail", "city": "Hinesville", "state": "GA"},
    {"name": "Lincoln County Detention", "city": "Carrizozo", "state": "NM"},
    {"name": "Little River County Detention Facility", "city": "Ashdown", "state": "AR"},
    {"name": "Livingston IAH Adult Detention Center (TX)", "city": "Livingston", "state": "TX"},
    {"name": "Livingston Parish Detention Center", "city": "Livingston", "state": "LA"},
    {"name": "Livingston Parish Work Release", "city": "Walker", "state": "LA"},
    {"name": "Madison Correctional JV3", "city": "Tallulah", "state": "LA"},
    {"name": "Madison JV4 (Southern Corr)", "city": "Tallulah", "state": "LA"},
    {"name": "Madison Parish Detention Center (Men's)", "city": "Tallulah", "state": "LA"},
    {"name": "Madison Parish Jail", "city": "Tallulah", "state": "LA"},
    {"name": "Madison Parish LTCW (Women's facility)", "city": "Tallulah", "state": "LA"},
    {"name": "McIntosh County Jail", "city": "Darien", "state": "GA"},
    {"name": "Miller County Jail", "city": "Texarkana", "state": "AR"},
    {"name": "Moore County Detention Facility", "city": "Lynchburg", "state": "TN"},
    {"name": "Morgan City Jail", "city": "Morgan City", "state": "LA"},
    {"name": "Nassau County Jail", "city": "Yulee", "state": "FL"},
    {"name": "Ouachita Correctional Center", "city": "Monroe", "state": "LA"},
    {"name": "Ouachita Parish Work Release", "city": "Monroe", "state": "LA"},
    {"name": "Patterson City Jail", "city": "Patterson", "state": "LA"},
    {"name": "Perry County Detention", "city": "Perryville", "state": "AR"},
    {"name": "Phelps Correctional Center", "city": "Dequincy", "state": "LA"},
    {"name": "Poinsett County Detention Center", "city": "Harrisburg ", "state": "AR"},
    {"name": "Pointe Coupee Detention Center", "city": "New Roads", "state": "LA"},
    {"name": "Pope County Detention Center", "city": "Russellville", "state": "AR"},
    {"name": "Prairieland Detention Center", "city": "Alvarado", "state": "TX"},
    {"name": "Presidio County Jail", "city": "Marfa", "state": "TX"},
    {"name": "Pulaski County Regional Detention", "city": "Little Rock", "state": "AR"},
    {"name": "Richland Parish Detention Center", "city": "Rayville", "state": "LA"},
    {"name": "Richwood Correctional Center", "city": "Monroe", "state": "LA"},
    {"name": "River Correctional", "city": "Ferriday", "state": "LA"},
    {"name": "Rolling Plains Detention Center", "city": "Haskell", "state": "TX"},
    {"name": "San Luis Regional Detention Center", "city": "San Luis", "state": "AZ"},
    {"name": "Sebastian County Detention Center", "city": "Fort Smith", "state": "AR"},
    {"name": "Springhill Police Department", "city": "Springhill", "state": "LA"},
    {"name": "St Louis CJC-MSI", "city": "St Louis", "state": "MO"},
    {"name": "Sumter County LEC", "city": "Americus", "state": "GA"},
    {"name": "Taylor County Detention", "city": "Abilene", "state": "TX"},
    {"name": "Tensas Parish Detention Center", "city": "Waterproof", "state": "LA"},
    {"name": "Tulsa - David L. Moss", "city": "Tulsa", "state": "OK"},
    {"name": "Union Parish Detention Center", "city": "Farmerville", "state": "LA"},
    {"name": "Van Zandt County", "city": "Canton", "state": "TX"},
    {"name": "Washington County Detention", "city": "Fayetteville", "state": "AR"},
    {"name": "Wayne County Jail", "city": "Jessup", "state": "GA"},
    {"name": "Webster Parish Jail", "city": "Minden", "state": "LA"},
    {"name": "West Carroll Parish Jail", "city": "Oak Grove", "state": "LA"},
    {"name": "West Texas Detention Center", "city": "Sierra Blanca", "state": "TX"},
    {"name": "White County Detention Center", "city": "Searcy", "state": "AR"},
    {"name": "Williamson County Detention Facility", "city": "Georgetown", "state": "TX"},
    {"name": "Winn Correctional Center", "city": "Winnfield", "state": "LA"},
    {"name": "Winn Parish Jail", "city": "Winnfield", "state": "LA"},
    {"name": "Winnfield City Jail", "city": "Winnfield", "state": "LA"},
    {"name": "Wise County Detention Center", "city": "Decatur", "state": "TX"},
  ]
};

Array.prototype.push.apply(window.allFacilities, getFacilities());